name: "Build and Push Docker image"
on: 
    push:
        branches: 
            - main
# env:
#     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#     DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "Login to Docker Hub"
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            - name: "Build Docker image"
              run: docker build ./ -t my-docker-image 
            - name: "Tag Docker image"
              run: docker tag my-docker-image ${{ secrets.DOCKER_REPO }}/my-docker-image
            - name: "Push Docker image"
              run: docker push ${{ secrets.DOCKER_REPO }}/my-docker-image
        


